### ISSUE TITLE
Allow long press on buttons "+" and "-"

### ISSUE THREAD

**Issue by guillaumecardon** [Basssiiie/OpenRCT2-RideVehicleEditor#21]
Hello,

When you want to modify to track progress, you need to click much and much time on buttons "+" and "-" to increase or decrease value.
It could be great to stay clicked on buttons until we had the wanted value.

Thanks

**Comment by Basssiiie** [comment]
Hey, thank you for your suggestion!

Unfortunately currently the plugin API does not offer any way to check whether the button is held down for a longer time ([see here](https://github.com/OpenRCT2/OpenRCT2/blob/8c5cd61b6969ba3cfec578d4cdfea1f239985fd1/distribution/openrct2.d.ts#L1952)), so this feature would require changes to the OpenRCT2 source code and plugin API itself. This makes it a bit more work to implement something like this.

As an alternative, you can use the dropdown marked in the picture below to increase the strength of the [+] and [-] buttons, so instead of +1 and -1 it will do +10 and -10 for example. Hope it helps! 😃 

![afbeelding](https://user-images.githubusercontent.com/20048660/105830776-327abd00-5fc6-11eb-8d5b-548215a93b6d.png)

**Comment by guillaumecardon** [comment]
Oh yes, i didn't know this feature, thanks !

**Comment by Basssiiie** [comment]
A bit of a late update, but it is now possible to hold down the [+] and [-] buttons. [See here](https://github.com/OpenRCT2/OpenRCT2/pull/14171). It was added to OpenRCT2 on the 27th of February to all plugin-based spinners and is available on both develop and release versions. :)
